package edu.ucsd.cse110.successorator;

import android.content.Context;

import java.util.Calendar;

/**
 * Generated by ChatGPT,
 */
public class TimeManager {
    private final Context context;

    public TimeManager(Context context) {
        this.context = context;
    }

    public boolean isAfter2AM() {
        Calendar currentTime = Calendar.getInstance();
        int currentHour = currentTime.get(Calendar.HOUR_OF_DAY);
        return currentHour >= 2;
    }
}

